# Generated by Django 2.0.6 on 2018-07-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20180706_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
    ]
