# Generated by Django 2.0.6 on 2018-07-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
