# Generated by Django 2.0.6 on 2018-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180711_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdown_content',
            field=models.TextField(default='', verbose_name='markdown内容'),
            preserve_default=False,
        ),
    ]
